name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/ivanrybin/algorithms_go
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ${{ env.GOPATH }}/src/github.com/ivanrybin/algorithms_go

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Debug
        run: |
          go version
          go env

      - name: Test
        run: make test
